# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.0"
slug: example
description: Example add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
# Added
map:
  - config
  - addon_configs
options:
  - media_folder: "camterraza"
  - tf_labels: "con,sin"
  - tf_label_invoke: "con"
  - hassio_webhookurl: "replaceme with another webhook automation full URL"