# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.2"
slug: example
description: Example add-on
url: "https://github.com/fontanon/hassio-addon-test/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - homeassistant_config
  - addon_config
options:
  media_folder: "camterraza"
  tf_labels: "con,sin"
  tf_label_invoke: "con"
  hassio_webhookurl: "replaceme with another webhook automation full URL"
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"